version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  nginx:
    image: "i-nginx:1.0.0"
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - mynetwork
