version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  nginx:
    image: "i-nginx:1.0.0"
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - mynetwork
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    image: "i-wordpress:1.0.0"
    build: ./requirements/wordpress
    restart: always
    expose:
      - "9000"
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    image: "i-mariadb:1.0.0"
    build: ./requirements/mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - mynetwork
    env_file:
      - .env
    volumes:
      - mariadb_data:/data


volumes:
  mariadb_data:
    driver: local
    name: wp_db
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/aaa

  wordpress_data:
    driver: local
    name: wp_files
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/aaa
