version: '3'



services:
  nginx:
    image: nginx
    build: srcs/requirements/nginx
    ports:
      - "443:443"
    networks:
      - network

  wordpress:
    image: wordpress
    build: srcs/requirements/wordpress
    ports:
      - "9000:9000"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
